// packages/react-view-split/index.js
import React, { useState, Children, cloneElement } from "react";
import { handleMouseDown, buildSystem } from "html-view-split";

export function SplitView({ children, options }) {
  const state = useState(function () {
    return buildSystem(Children.count(children), options || {});
  });
  const system = state[0];
  const updateSystem = state[1];

  function updateSizes(position, sizes) {
    updateSystem((oldSystem) => {
      const newSystem = {};
      for (var key in oldSystem) {
        newSystem[key] = oldSystem[key];
      }
      for (let i = 0; i < newSystem.sizes.length; ++i) {
        if (i == position - 1) {
          newSystem.sizes[i] = sizes[0];
        }
        if (i == position) {
          newSystem.sizes[i] = sizes[1];
        }
      }
      return newSystem;
    });
  }

  function capturePosition(position) {
    return function (event) {
      handleMouseDown(position, event, system, updateSizes);
    };
  }

  const dividends = [];

  for (
    let position = 0, length = Children.count(children);
    position < length;
    ++position
  ) {
    if (position != 0) {
      dividends.push(
        <div
          className="divider"
          onMouseDown={capturePosition(position)}
          onTouchStart={capturePosition(position)}
          style={{ [system.elementDimension]: `${system.dividerSize}px` }}
        />
      );
    }

    dividends.push(
      cloneElement(children[position], {
        style: {
          [system.elementDimension]: `calc(${system.sizes[position]}% - ${system.panelSpaceForDivider}px)`,
        },
      })
    );
  }

  return <div className="split-view">{dividends}</div>;
}

// packages/vue-view-split/index.vue
<script>
import { handleMouseDown, buildSystem } from "html-view-split";

export default {
  props: ["options"],
  data() {
    return {
      system: buildSystem(this.$slots.default.length, this.options || {}),
    };
  },
  methods: {
    startResize(event, position) {
      handleMouseDown(position, event, this.system, this.paintScreen);
    },
    paintScreen(position, updatedSizes) {
      for (let i = 0; i < this.system.sizes.length; i++) {
        if (i == position - 1) {
          this.$set(this.system.sizes, i, updatedSizes[0]);
        }
        if (i == position) {
          this.$set(this.system.sizes, i, updatedSizes[1]);
        }
      }
    },
  },
  render: function (h) {
    const dividends = [];

    for (let position = 0; position < this.$slots.default.length; ++position) {
      if (position != 0) {
        dividends.push(
          h("div", {
            class: "divider",
            style: {
              [this.system.elementDimension]: `${this.system.dividerSize}px`,
            },
            on: {
              mousedown: (event) => this.startResize(event, position),
              touchstart: (event) => this.startResize(event, position),
            },
          })
        );
      }

      dividends.push(
        h(
          "div",
          {
            style: {
              [this.system
                .elementDimension]: `calc(${this.system.sizes[position]}% - ${this.system.panelSpaceForDivider}px)`,
            },
          },
          [this.$slots.default[position]]
        )
      );
    }

    return h(
      "div",
      {
        class: "split-view",
      },
      [dividends]
    );
  },
};
</script>
